name: Docker Image CI

on:
  push:
    branches: [ master ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag shakilnsu2018/docker-react
    - name: Run Test
      run: docker run -e CI=true shakilnsu2018/docker-react npm run test -- --coverage
